language: python

git:
  quiet: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install espeak
  - python -m pip install --upgrade pip
  - pip install six==1.12.0

matrix:
  include:
  - name: "Lint check"
    python: "3.6"
    install: pip install --quiet --upgrade cardboardlint pylint
    env: TEST_SUITE="lint"
  - name: "Unit tests"
    python: "3.6"
    install:
      - python setup.py egg_info
      - pip install -e .
    env: TEST_SUITE="unittest"
  - name: "Unit tests"
    python: "3.6"
    install:
      - python setup.py egg_info
      - pip install -e .
    env: TEST_SUITE="testscripts"

script: ./.travis/script
