blank_issues_enabled: false
contact_links:
  - name: CoquiTTS GitHub Discussions
    url: https://github.com/coqui-ai/TTS/discussions
    about: Please ask and answer questions here.
  - name: Coqui Security issue disclosure
    url: mailto:info@coqui.ai
    about: Please report security vulnerabilities here.
