name: data-tests

on:
  push:
    branches:
      - energy
jobs:
  measure-energy:
    runs-on: ubuntu-latest
    name: A job to measure energy
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'requirements*'
      - name: check OS
        run: cat /etc/os-release
      - name: set ENV
        run: export TRAINER_TELEMETRY=0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git make gcc
          make system-deps
      - name: Install/upgrade Python setup deps
        run: python3 -m pip install --upgrade pip setuptools wheel
      - name: Replace scarf urls
        run: |
          sed -i 's/https:\/\/coqui.gateway.scarf.sh\//https:\/\/github.com\/coqui-ai\/TTS\/releases\/download\//g' TTS/.models.json
      - name: Install TTS
        run: |
          python3 -m pip install .[all]
          python3 setup.py egg_info

      - name: Measure unit test energy
        uses: koenhagen/measure-energy-action@v0.4
        with:
          what-to-test: make data_tests
